### ISSUE TITLE
PID appears in menu even if pre-execution prompt is canceled

### ISSUE THREAD

**Issue by aaplmath** [aaplmath/Caffeinator#2]
### Issue

If "Prompt Before Executing" is enabled and the user open the process-based Caffeination dialog, enters a PID, but then cancels the Caffeination on the pre-execution prompt, the text of the "Caffeinate a Process…" label will still change to "Caffeinating [App Name/PID]" in the Caffeinator menu. This is because the change to the text is occurring in `processClicked`, which is unaware of the possibility of cancelation in `generateCaffeine`.

### Steps to Reproduce

* Enable "Prompt Before Executing" in the "Advanced" menu
* Select "Caffeinate a Process…" and enter a PID
* On the prompt that follows, select "Cancel"

### Proposed Resolution

The process name lookup and label text changing should probably occur in `generateCaffeine`, after ensuring that the Caffeination has not been canceled in the pre-execution prompt.

**Comment by thefangbear** [comment]
Maybe you should tune your `kP`, `kI`, and `kD` so that your program is more responsive to subtle, transient changes. Time to hire a control system engineer 💯  💯

**Comment by aaplmath** [comment]
Resolved as of 3a1fb52.
